import { SearchResult } from "../types";

export function generateNotebook(results: SearchResult): string {
  const notebook = {
    cells: [
      {
        cell_type: "markdown",
        metadata: {},
        source: [
          "# EarthLens AI: Research Starter Notebook\n",
          "## Analysis for: " + (results.explanation.split('.')[0] || "Earth Science Query") + "\n",
          "\n",
          "This notebook was automatically generated by EarthLens AI to help you jumpstart your research using NASA Earthdata.\n",
          "\n",
          "### Research Context\n",
          results.explanation + "\n"
        ]
      },
      {
        cell_type: "code",
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          "# Configuration\n",
          "NASA_API_KEY = 'YOUR_NASA_API_KEY_HERE'  # Replace with your actual key if not set in environment\n",
          "DATASET_IDS = " + JSON.stringify(results.datasets.map(d => d.id), null, 2) + "\n",
          "VARIABLES = " + JSON.stringify(results.suggestedVariables, null, 2) + "\n"
        ]
      },
      {
        cell_type: "markdown",
        metadata: {},
        source: [
          "### 1. Setup and Authentication\n",
          "We'll use `requests` to interact with the NASA CMR API and `pydap` or `xarray` for data handling."
        ]
      },
      {
        cell_type: "code",
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          "import requests\n",
          "import json\n",
          "import pandas as pd\n",
          "\n",
          "def get_dataset_details(concept_id):\n",
          "    url = f'https://cmr.earthdata.nasa.gov/search/concepts/{concept_id}.json'\n",
          "    headers = {'x-api-key': NASA_API_KEY} if NASA_API_KEY != 'YOUR_NASA_API_KEY_HERE' else {}\n",
          "    response = requests.get(url, headers=headers)\n",
          "    return response.json()\n",
          "\n",
          "# Fetch metadata for recommended datasets\n",
          "metadata_list = []\n",
          "for cid in DATASET_IDS:\n",
          "    try:\n",
          "        meta = get_dataset_details(cid)\n",
          "        metadata_list.append(meta)\n",
          "        print(f\"Fetched metadata for: {meta.get('title', cid)}\")\n",
          "    except Exception as e:\n",
          "        print(f\"Error fetching {cid}: {e}\")"
        ]
      },
      {
        cell_type: "markdown",
        metadata: {},
        source: [
          "### 2. Data Access Strategy\n",
          "NASA data is often accessible via OPeNDAP or direct S3 access (if running in AWS us-west-2)."
        ]
      },
      {
        cell_type: "code",
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [
          "print(\"Recommended variables for analysis:\")\n",
          "for var in VARIABLES:\n",
          "    print(f\"- {var}\")\n",
          "\n",
          "# Example: Search for granules (data files)\n",
          "def search_granules(concept_id, limit=5):\n",
          "    url = 'https://cmr.earthdata.nasa.gov/search/granules.json'\n",
          "    params = {\n",
          "        'concept_id': concept_id,\n",
          "        'page_size': limit\n",
          "    }\n",
          "    response = requests.get(url, params=params)\n",
          "    return response.json().get('feed', {}).get('entry', [])\n",
          "\n",
          "first_dataset_granules = search_granules(DATASET_IDS[0])\n",
          "print(f\"\\nFound {len(first_dataset_granules)} granules for the primary dataset.\")"
        ]
      }
    ],
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3"
      },
      language_info: {
        codemirror_mode: {
          name: "ipython",
          version: 3
        },
        file_extension: ".py",
        mimetype: "text/x-python",
        name: "python",
        nbconvert_exporter: "python",
        pygments_lexer: "ipython3",
        version: "3.8.5"
      }
    },
    nbformat: 4,
    nbformat_minor: 4
  };

  return JSON.stringify(notebook, null, 2);
}
